/*
 * Customers.PCL
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 09/17/2014
 */
using System;

namespace Customers.PCL
{
    public class Configuration
    {
        //The base Uri for API calls
        public const string BaseUri = "http://demodev.espressologic.com/rest/el-dev/jcbtx/v1";

    }
}