# This file was automatically generated by APIMATIC BETA v2.0 on 09/17/2014
require 'openssl'
require 'json'
require 'unirest'

# APIMATIC Helper Files
require 'customers/api_helper.rb'
require 'customers/api_exception.rb'
require 'customers/configuration.rb'

# Controllers
require 'customers/controllers/api_controller.rb'

# Models
require 'customers/models/customers_model.rb'
