/*
 * Customers.PCL
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 09/17/2014
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Customers.PCL;

namespace Customers.PCL.Models
{
    public class CustomersModel : INotifyPropertyChanged 
    {
        // These fields hold the values for the public properties.
        private string phone;
        private string contactName;
        private string fax;
        private string companyName;
        private string country;
        private string contactTitle;
        private string city;
        private string region;
        private string postalCode;
        private int customerID;
        private string address;
        private int balance;
        private int creditLimit;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Phone")]
        public string Phone 
        { 
            get 
            {
                return this.phone; 
            } 
            set 
            {
                this.phone = value;
                onPropertyChanged("Phone");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ContactName")]
        public string ContactName 
        { 
            get 
            {
                return this.contactName; 
            } 
            set 
            {
                this.contactName = value;
                onPropertyChanged("ContactName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Fax")]
        public string Fax 
        { 
            get 
            {
                return this.fax; 
            } 
            set 
            {
                this.fax = value;
                onPropertyChanged("Fax");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("CompanyName")]
        public string CompanyName 
        { 
            get 
            {
                return this.companyName; 
            } 
            set 
            {
                this.companyName = value;
                onPropertyChanged("CompanyName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Country")]
        public string Country 
        { 
            get 
            {
                return this.country; 
            } 
            set 
            {
                this.country = value;
                onPropertyChanged("Country");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("ContactTitle")]
        public string ContactTitle 
        { 
            get 
            {
                return this.contactTitle; 
            } 
            set 
            {
                this.contactTitle = value;
                onPropertyChanged("ContactTitle");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("City")]
        public string City 
        { 
            get 
            {
                return this.city; 
            } 
            set 
            {
                this.city = value;
                onPropertyChanged("City");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Region")]
        public string Region 
        { 
            get 
            {
                return this.region; 
            } 
            set 
            {
                this.region = value;
                onPropertyChanged("Region");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("PostalCode")]
        public string PostalCode 
        { 
            get 
            {
                return this.postalCode; 
            } 
            set 
            {
                this.postalCode = value;
                onPropertyChanged("PostalCode");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("CustomerID")]
        public int CustomerID 
        { 
            get 
            {
                return this.customerID; 
            } 
            set 
            {
                this.customerID = value;
                onPropertyChanged("CustomerID");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Address")]
        public string Address 
        { 
            get 
            {
                return this.address; 
            } 
            set 
            {
                this.address = value;
                onPropertyChanged("Address");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Balance")]
        public int Balance 
        { 
            get 
            {
                return this.balance; 
            } 
            set 
            {
                this.balance = value;
                onPropertyChanged("Balance");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("CreditLimit")]
        public int CreditLimit 
        { 
            get 
            {
                return this.creditLimit; 
            } 
            set 
            {
                this.creditLimit = value;
                onPropertyChanged("CreditLimit");
            }
        }

        /// <summary>
        /// Property changed event for observer pattern
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;

        /// <summary>
        /// Raises event when a property is changed
        /// </summary>
        /// <param name="propertyName">Name of the changed property</param>
        protected void onPropertyChanged(String propertyName)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
} 