//
//  APIException.h
//  Customers
//
//  This file was automatically generated by APIMATIC BETA v2.0 on 09/17/2014
//
#ifndef APIEXCEPTION
#define APIEXCEPTION

#import <Foundation/Foundation.h>

@interface APIException : NSException

/**
* The HTTP response code from the API request
*/
@property NSInteger responseCode;

/**
* Initialization
* @param	name	The name of the exception
* @param	reason	The reason for throwing exception
* @param	code	The HTTP response code from the API request
* @param	body	The HTTP response body from the API request
*/
- (APIException*) initWithName: (NSString*) name
                     andReason: (NSString*) reason
                       andCode: (NSInteger) code;

@end

#endif