//
//  Configuration.h
//  Customers
//
//  This file was automatically generated by APIMATIC BETA v2.0 on 09/17/2014
//
#ifndef Customers_Configuration_h
#define Customers_Configuration_h

/** The base Uri for API calls */
static const NSString* Configuration_BaseUri = @"http://demodev.espressologic.com/rest/el-dev/jcbtx/v1";

#endif
