'''
CustomersLib
This file was automatically generated by APIMATIC BETA v2.0 on 09/17/2014
'''

class Configuration :
    #The base Uri for API calls
    BASEURI = "http://demodev.espressologic.com/rest/el-dev/jcbtx/v1"


