'''
   CustomersLib
 
   This file was automatically generated by APIMATIC BETA v2.0 on 09/17/2014
'''

class CustomersModel():

    def __init__(self):   
        self.phone = None        
        self.contactName = None        
        self.fax = None        
        self.companyName = None        
        self.country = None        
        self.contactTitle = None        
        self.city = None        
        self.region = None        
        self.postalCode = None        
        self.customerID = None        
        self.address = None        
        self.balance = None        
        self.creditLimit = None        

 
    def getPhone(self): 
        '''
        TODO: Write general description for this method

        :rtype: string
        '''
        return self.phone;
    
    

    def setPhone(self,value): 
        self.phone = value;
     
 
    def getContactName(self): 
        '''
        TODO: Write general description for this method

        :rtype: string
        '''
        return self.contactName;
    
    

    def setContactName(self,value): 
        self.contactName = value;
     
 
    def getFax(self): 
        '''
        TODO: Write general description for this method

        :rtype: string
        '''
        return self.fax;
    
    

    def setFax(self,value): 
        self.fax = value;
     
 
    def getCompanyName(self): 
        '''
        TODO: Write general description for this method

        :rtype: string
        '''
        return self.companyName;
    
    

    def setCompanyName(self,value): 
        self.companyName = value;
     
 
    def getCountry(self): 
        '''
        TODO: Write general description for this method

        :rtype: string
        '''
        return self.country;
    
    

    def setCountry(self,value): 
        self.country = value;
     
 
    def getContactTitle(self): 
        '''
        TODO: Write general description for this method

        :rtype: string
        '''
        return self.contactTitle;
    
    

    def setContactTitle(self,value): 
        self.contactTitle = value;
     
 
    def getCity(self): 
        '''
        TODO: Write general description for this method

        :rtype: string
        '''
        return self.city;
    
    

    def setCity(self,value): 
        self.city = value;
     
 
    def getRegion(self): 
        '''
        TODO: Write general description for this method

        :rtype: string
        '''
        return self.region;
    
    

    def setRegion(self,value): 
        self.region = value;
     
 
    def getPostalCode(self): 
        '''
        TODO: Write general description for this method

        :rtype: string
        '''
        return self.postalCode;
    
    

    def setPostalCode(self,value): 
        self.postalCode = value;
     
 
    def getCustomerID(self): 
        '''
        TODO: Write general description for this method

        :rtype: int
        '''
        return self.customerID;
    
    

    def setCustomerID(self,value): 
        self.customerID = value;
     
 
    def getAddress(self): 
        '''
        TODO: Write general description for this method

        :rtype: string
        '''
        return self.address;
    
    

    def setAddress(self,value): 
        self.address = value;
     
 
    def getBalance(self): 
        '''
        TODO: Write general description for this method

        :rtype: int
        '''
        return self.balance;
    
    

    def setBalance(self,value): 
        self.balance = value;
     
 
    def getCreditLimit(self): 
        '''
        TODO: Write general description for this method

        :rtype: int
        '''
        return self.creditLimit;
    
    

    def setCreditLimit(self,value): 
        self.creditLimit = value;
     
 