# This file was automatically generated by APIMATIC BETA v2.0 on 09/17/2014

module Customers
  class CustomersModel

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :Phone

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :ContactName

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :Fax

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :CompanyName

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :Country

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :ContactTitle

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :City

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :Region

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :PostalCode

    # TODO: Write general description for this method
    # @return [Numeric]
    attr_accessor :CustomerID

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :Address

    # TODO: Write general description for this method
    # @return [Numeric]
    attr_accessor :Balance

    # TODO: Write general description for this method
    # @return [Numeric]
    attr_accessor :CreditLimit

    
    def method_missing (method_name)
      puts "there's no method called '#{method_name}'"
    end

  end
end