<?php
/*
 * CustomersLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 09/17/2014
 */
// This snippet is adopted from Stripe SDK.
if (!function_exists('curl_init')) {
  throw new Exception('CustomersLib needs the CURL PHP extension.');
}
if (!function_exists('json_decode')) {
  throw new Exception('CustomersLib needs the JSON PHP extension.');
}
if (!function_exists('mb_detect_encoding')) {
  throw new Exception('CustomersLib needs the Multibyte String PHP extension.');
}

// This dependency shall be resolved by composer
require_once('packages/apimatic/unirest-php/lib/Unirest.php');

// APIMATIC Helper Files
require_once(dirname(__FILE__) . '/CustomersLib/APIHelper.php');
require_once(dirname(__FILE__) . '/CustomersLib/APIException.php');
require_once(dirname(__FILE__) . '/CustomersLib/Configuration.php');

// Controllers
require_once(dirname(__FILE__) . '/CustomersLib/Controllers/APIController.php');

// Models
require_once(dirname(__FILE__) . '/CustomersLib/Models/CustomersModel.php');
