/*
 * CustomersLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 09/17/2014
 */
package io.apimatic.customerslib.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class CustomersModel 
        extends java.util.Observable {

    private String phone;
    private String contactName;
    private String fax;
    private String companyName;
    private String country;
    private String contactTitle;
    private String city;
    private String region;
    private String postalCode;
    private int customerID;
    private String address;
    private int balance;
    private int creditLimit;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Phone")
    public String getPhone ( ) { 
        return this.phone;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Phone")
    public void setPhone (String value) { 
        this.phone = value;
        notifyObservers(this.phone);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("ContactName")
    public String getContactName ( ) { 
        return this.contactName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("ContactName")
    public void setContactName (String value) { 
        this.contactName = value;
        notifyObservers(this.contactName);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Fax")
    public String getFax ( ) { 
        return this.fax;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Fax")
    public void setFax (String value) { 
        this.fax = value;
        notifyObservers(this.fax);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("CompanyName")
    public String getCompanyName ( ) { 
        return this.companyName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("CompanyName")
    public void setCompanyName (String value) { 
        this.companyName = value;
        notifyObservers(this.companyName);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Country")
    public String getCountry ( ) { 
        return this.country;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Country")
    public void setCountry (String value) { 
        this.country = value;
        notifyObservers(this.country);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("ContactTitle")
    public String getContactTitle ( ) { 
        return this.contactTitle;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("ContactTitle")
    public void setContactTitle (String value) { 
        this.contactTitle = value;
        notifyObservers(this.contactTitle);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("City")
    public String getCity ( ) { 
        return this.city;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("City")
    public void setCity (String value) { 
        this.city = value;
        notifyObservers(this.city);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Region")
    public String getRegion ( ) { 
        return this.region;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Region")
    public void setRegion (String value) { 
        this.region = value;
        notifyObservers(this.region);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("PostalCode")
    public String getPostalCode ( ) { 
        return this.postalCode;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("PostalCode")
    public void setPostalCode (String value) { 
        this.postalCode = value;
        notifyObservers(this.postalCode);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("CustomerID")
    public int getCustomerID ( ) { 
        return this.customerID;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("CustomerID")
    public void setCustomerID (int value) { 
        this.customerID = value;
        notifyObservers(this.customerID);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Address")
    public String getAddress ( ) { 
        return this.address;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Address")
    public void setAddress (String value) { 
        this.address = value;
        notifyObservers(this.address);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("Balance")
    public int getBalance ( ) { 
        return this.balance;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("Balance")
    public void setBalance (int value) { 
        this.balance = value;
        notifyObservers(this.balance);
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("CreditLimit")
    public int getCreditLimit ( ) { 
        return this.creditLimit;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("CreditLimit")
    public void setCreditLimit (int value) { 
        this.creditLimit = value;
        notifyObservers(this.creditLimit);
    }
 
}
 