# This file was automatically generated by APIMATIC BETA v2.0 on 09/17/2014

module Customers 
  class Configuration

    # The base Uri for API calls
    BASE_URI = "http://demodev.espressologic.com/rest/el-dev/jcbtx/v1"


  end
end
