//
//  CustomersModel.h
//  Customers
//
//  This file was automatically generated by APIMATIC BETA v2.0 on 09/17/2014
//
#ifndef CUSTOMERSMODEL
#define CUSTOMERSMODEL

#import <Foundation/Foundation.h>
#import "JSONModel.h"
#import "APIHelper.h"


//protocol defined for deserialization of JSON
@protocol CustomersModel
@end

@interface CustomersModel : JSONModel

/**
* TODO: Write general description for this method
*/
@property NSString* phone;

/**
* TODO: Write general description for this method
*/
@property NSString* contactName;

/**
* TODO: Write general description for this method
*/
@property NSString* fax;

/**
* TODO: Write general description for this method
*/
@property NSString* companyName;

/**
* TODO: Write general description for this method
*/
@property NSString* country;

/**
* TODO: Write general description for this method
*/
@property NSString* contactTitle;

/**
* TODO: Write general description for this method
*/
@property NSString* city;

/**
* TODO: Write general description for this method
*/
@property NSString* region;

/**
* TODO: Write general description for this method
*/
@property NSString* postalCode;

/**
* TODO: Write general description for this method
*/
@property int customerID;

/**
* TODO: Write general description for this method
*/
@property NSString* address;

/**
* TODO: Write general description for this method
*/
@property int balance;

/**
* TODO: Write general description for this method
*/
@property int creditLimit;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap;

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper;

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName;

@end

#endif