//
//  CustomersModel.m
//  Customers
//
//  This file was automatically generated by APIMATIC BETA v2.0 on 09/17/2014
//
#import "CustomersModel.h"

@implementation CustomersModel

/**
* TODO: Write general description for this method
*/
@synthesize phone;

/**
* TODO: Write general description for this method
*/
@synthesize contactName;

/**
* TODO: Write general description for this method
*/
@synthesize fax;

/**
* TODO: Write general description for this method
*/
@synthesize companyName;

/**
* TODO: Write general description for this method
*/
@synthesize country;

/**
* TODO: Write general description for this method
*/
@synthesize contactTitle;

/**
* TODO: Write general description for this method
*/
@synthesize city;

/**
* TODO: Write general description for this method
*/
@synthesize region;

/**
* TODO: Write general description for this method
*/
@synthesize postalCode;

/**
* TODO: Write general description for this method
*/
@synthesize customerID;

/**
* TODO: Write general description for this method
*/
@synthesize address;

/**
* TODO: Write general description for this method
*/
@synthesize balance;

/**
* TODO: Write general description for this method
*/
@synthesize creditLimit;


/**
* Key mappings for the json serialization and deserialization
*/
+(NSDictionary*) keyMap
{
    NSMutableDictionary* map = [[NSMutableDictionary alloc] init];
    [map addEntriesFromDictionary: @{
        @"Phone": @"phone",
        @"ContactName": @"contactName",
        @"Fax": @"fax",
        @"CompanyName": @"companyName",
        @"Country": @"country",
        @"ContactTitle": @"contactTitle",
        @"City": @"city",
        @"Region": @"region",
        @"PostalCode": @"postalCode",
        @"CustomerID": @"customerID",
        @"Address": @"address",
        @"Balance": @"balance",
        @"CreditLimit": @"creditLimit"  
    }];

    return map;
}

/**
* Key mapper for json serialization and deserialization
*/
+(JSONKeyMapper*) keyMapper
{ 
  return [[JSONKeyMapper alloc] initWithDictionary: [self keyMap]];
}

/**
* Helps avoiding deserialization errors when one or more properties are missing
* @returns	True, indicating that all properties are optional for deserialization
*/
+(BOOL)propertyIsOptional:(NSString*) propertyName
{
    return YES;
}

@end